site:
  title: Project_name
  url: /user-docs/index.html
  start_page: user-docs:index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: user-docs
  - url: ./
    branches: HEAD
    start_path: manual
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./site
  clean: true
asciidoc:
  attributes:
    lang: ru
    experimental: ''
    hide-uri-scheme: '@'
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    table-frame: 'none@'
    table-grid: 'rows@'
    kroki-server-url: https://kroki.io/
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
