site:
  title: Antora-test
  url: /user-docs/index.html
  start_page: ./user-docs/modules/ROOT/pages/index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: user-docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true